name: NSFS Ceph S3 Tests
on: 
  workflow_run:
    workflows: ["Build Noobaa Image"]
    types: 
      - completed

jobs:
  nsfs-ceph-s3-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: nadavMiz/noobaa-core
          path: 'noobaa-core'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: noobaa-tester
          path: /tmp
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: Load image
        run: docker load --input /tmp/noobaa-tester.tar

      - name: Run NSFS Ceph s3-tests
        run: |
          set -x
          cd ./noobaa-core
          mkdir -p logs/ceph-nsfs-test-logs
          chmod 777 logs/ceph-nsfs-test-logs
          make test-nsfs-cephs3 -o tester
